-- ============================================================================
-- Forward migration for dev-ecommerce
-- Generated by Taproot-RCA on 2026-04-06 21:40 UTC
-- Migration ID: 20260406214030
-- ============================================================================

BEGIN;

-- Start of forward migration
BEGIN;

ALTER TABLE public.orders ADD COLUMN tracking_number character varying;

COMMIT;

COMMIT;
