-- ============================================================================
-- Forward migration for dev-ecommerce
-- Generated by Taproot-RCA on 2026-04-13 16:27 UTC
-- Migration ID: 20260413162713
-- ============================================================================

BEGIN;

-- Start of forward migration script

BEGIN;

-- 1. Table removed: public.shipping_addresses
DROP TABLE IF EXISTS public.shipping_addresses CASCADE;

-- 2. Default changed: analytics.daily_revenue.avg_order_value (0 → none)
ALTER TABLE analytics.daily_revenue ALTER COLUMN avg_order_value DROP DEFAULT;

-- 3. Column removed: public.customers.name (was character varying)
ALTER TABLE public.customers DROP COLUMN name;

-- 4. Column removed: public.customers.phone (was character varying)
ALTER TABLE public.customers DROP COLUMN phone;

-- 5. Column removed: public.customers.birthday (was date)
ALTER TABLE public.customers DROP COLUMN birthday;

-- 6. Column added: public.customers.full_name (character varying)
ALTER TABLE public.customers ADD COLUMN full_name character varying;

-- 7. Column removed: public.order_items.discount_pct (was numeric)
ALTER TABLE public.order_items DROP COLUMN discount_pct;

-- 8. Column removed: public.orders.notes (was text)
ALTER TABLE public.orders DROP COLUMN notes;

-- 9. Column removed: public.orders.tracking_number (was character varying)
ALTER TABLE public.orders DROP COLUMN tracking_number;

-- 10. Nullable changed: public.orders.status (True → False)
ALTER TABLE public.orders ALTER COLUMN status SET NOT NULL;

COMMIT;

COMMIT;

-- Post-migration validation
-- Run these after applying the migration:

/*
-- Example query to check for data integrity in customers
SELECT * FROM public.customers WHERE full_name IS NULL;

-- Example query to verify nullable changes in orders
SELECT status FROM public.orders WHERE status IS NULL;
*/
