-- ============================================================================
-- Rollback migration for dev-ecommerce
-- Generated by Taproot-RCA on 2026-04-13 16:30 UTC
-- Migration ID: 20260413163045
-- ============================================================================

BEGIN;

-- Start of rollback script

BEGIN;

-- Drop new column: name from customers table
ALTER TABLE public.customers DROP COLUMN name;

-- Drop new column: discount_pct from order_items table
ALTER TABLE public.order_items DROP COLUMN discount_pct;

-- Nullable change for orders.status
ALTER TABLE public.orders ALTER COLUMN status SET NOT NULL;

-- Change default value of analytics.daily_revenue.avg_order_value back to its original value (if known)
-- Note: This assumes the original default value was not explicitly set in the migration script.
-- If it was, you would need to retrieve it from the database or use a different approach.

-- Drop new table: shipping_addresses
DROP TABLE public.shipping_addresses;

COMMIT;

COMMIT;
