-- ============================================================================
-- Rollback migration for dev-ecommerce
-- Generated by Taproot-RCA on 2026-04-13 16:36 UTC
-- Migration ID: 20260413163615
-- ============================================================================

BEGIN;

-- Start of rollback migration script

BEGIN;

-- Drop new column name from customers table
ALTER TABLE public.customers DROP COLUMN name;

-- Drop new column discount_pct from order_items table
ALTER TABLE public.order_items DROP COLUMN discount_pct;

-- Change nullable status of orders.status back to False
ALTER TABLE public.orders ALTER COLUMN status SET NULL;

-- Update default value for analytics.daily_revenue.avg_order_value back to its original value (if known)
-- This step assumes you have a backup or can determine the original value

-- Drop new table shipping_addresses
DROP TABLE public.shipping_addresses;

COMMIT;

COMMIT;
