-- ============================================================================
-- Rollback migration for dev-ecommerce
-- Generated by Taproot-RCA on 2026-04-13 16:27 UTC
-- Migration ID: 20260413162713
-- ============================================================================

BEGIN;

-- Start of rollback migration script

BEGIN;

-- 1. Table added: public.shipping_addresses
CREATE TABLE IF NOT EXISTS public.shipping_addresses (
    id serial PRIMARY KEY,
    customer_id integer REFERENCES customers(id),
    address_line1 text,
    address_line2 text,
    city text,
    state text,
    zip_code text,
    country text
);

-- 2. Default changed: analytics.daily_revenue.avg_order_value (none → 0)
ALTER TABLE analytics.daily_revenue ALTER COLUMN avg_order_value SET DEFAULT 0;

-- 3. Column added: public.customers.name (character varying)
ALTER TABLE public.customers ADD COLUMN name character varying;

-- 4. Column added: public.customers.phone (character varying)
ALTER TABLE public.customers ADD COLUMN phone character varying;

-- 5. Column added: public.customers.birthday (date)
ALTER TABLE public.customers ADD COLUMN birthday date;

-- 6. Column removed: public.customers.full_name (character varying)
ALTER TABLE public.customers DROP COLUMN full_name;

-- 7. Column added: public.order_items.discount_pct (numeric)
ALTER TABLE public.order_items ADD COLUMN discount_pct numeric;

-- 8. Column added: public.orders.notes (text)
ALTER TABLE public.orders ADD COLUMN notes text;

-- 9. Column added: public.orders.tracking_number (character varying)
ALTER TABLE public.orders ADD COLUMN tracking_number character varying;

-- 10. Nullable changed: public.orders.status (False → True)
ALTER TABLE public.orders ALTER COLUMN status DROP NOT NULL;

COMMIT;

COMMIT;
