-- ============================================================================
-- Forward migration for dev-ecommerce
-- Generated by Taproot-RCA on 2026-04-13 16:36 UTC
-- Migration ID: 20260413163615
-- ============================================================================

BEGIN;

-- Start of forward migration script

BEGIN;

-- Add new table shipping_addresses
CREATE TABLE public.shipping_addresses (
    id SERIAL PRIMARY KEY,
    customer_id INT NOT NULL REFERENCES public.customers(id),
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    zip_code VARCHAR(20) NOT NULL,
    country VARCHAR(100) NOT NULL
);

-- Update default value for analytics.daily_revenue.avg_order_value
ALTER TABLE analytics.daily_revenue ALTER COLUMN avg_order_value SET DEFAULT 0;

-- Add new column name to customers table
ALTER TABLE public.customers ADD COLUMN name VARCHAR(255);

-- Add new column discount_pct to order_items table
ALTER TABLE public.order_items ADD COLUMN discount_pct NUMERIC;

-- Change nullable status of orders.status
ALTER TABLE public.orders ALTER COLUMN status SET NOT NULL;

COMMIT;

COMMIT;
